# Generated by Django 6.0.5 on 2026-06-01 05:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flow_volume', models.FloatField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], default='close', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DispenserUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('flow_volume', models.FloatField()),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='dispensers.dispenser')),
            ],
        ),
    ]
