# Generated by Django 6.0.5 on 2026-06-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenserusage',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
