# Generated by Django 6.0.5 on 2026-06-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensers', '0002_alter_dispenserusage_opened_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispenserusage',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
